# Generated by Django 4.2 on 2023-04-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0007_alter_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, to='dwitter.profile'),
        ),
    ]
