# Generated by Django 4.2 on 2023-04-15 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0009_alter_profile_follows_dweets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dweets',
            new_name='Dweet',
        ),
    ]
